name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to DigitalOcean Container Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Verify Login (Debug)
        run: docker info

      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/dawahlabs-registry/akhirah:${{ env.COMMIT_HASH }} .
          docker tag registry.digitalocean.com/dawahlabs-registry/akhirah:${{ env.COMMIT_HASH }} registry.digitalocean.com/dawahlabs-registry/akhirah:latest

      - name: Push Docker image to DOCR
        run: |
          docker push registry.digitalocean.com/dawahlabs-registry/akhirah:${{ env.COMMIT_HASH }}
          docker push registry.digitalocean.com/dawahlabs-registry/akhirah:latest

      - name: Update Cosmos Repo with New Image Tag
        run: |
          git clone https://github.com/dawahlabs/cosmos.git
          cd cosmos

          # Update the image tag in deployment.yaml inside apps/akhirah/
          sed -i "s|image: registry.digitalocean.com/dawahlabs-registry/akhirah:.*|image: registry.digitalocean.com/dawahlabs-registry/akhirah:${{ env.COMMIT_HASH }}|" apps/akhirah/deployment.yaml

          git config user.name "fayazp088"
          git config user.email "fayazp088@gmail.com"

          git add apps/akhirah/deployment.yaml
          git commit -m "Update Akhirah image to ${{ env.COMMIT_HASH }}"
          git push https://${{ secrets.GH_PAT }}@github.com/dawahlabs/cosmos.git main
